name: Broken Links

on:
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: '00 18 * * *'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v5

      - name: Restore lychee cache
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: cache-lychee-${{ github.ref_name }}-

      - name: Run lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --base . --cache -c 20 --max-cache-age 1d
          fail: false

      - name: Save lychee cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.ref_name }}-${{ github.sha }}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          token: ${{ secrets.GITHUB_TOKEN }}
